// Code generated by fastssz. DO NOT EDIT.
// Hash: 0df537d3a622b77eec1f8456fc3b573c54449ca14e67a88055b8ff5e484e22bb
// Version: 0.1.3
package testcases

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the Vec object
func (v *Vec) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(v)
}

// MarshalSSZTo ssz marshals the Vec object to a target array
func (v *Vec) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(52)

	// Field (0) 'Values'
	if size := len(v.Values); size != 6 {
		err = ssz.ErrVectorLengthFn("Vec.Values", size, 6)
		return
	}
	for ii := 0; ii < 6; ii++ {
		dst = ssz.MarshalUint64(dst, v.Values[ii])
	}

	// Offset (1) 'Values2'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(v.Values2) * 4

	// Field (1) 'Values2'
	if size := len(v.Values2); size > 100 {
		err = ssz.ErrListTooBigFn("Vec.Values2", size, 100)
		return
	}
	for ii := 0; ii < len(v.Values2); ii++ {
		dst = ssz.MarshalUint32(dst, v.Values2[ii])
	}

	return
}

// UnmarshalSSZ ssz unmarshals the Vec object
func (v *Vec) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 52 {
		return ssz.ErrSize
	}

	tail := buf
	var o1 uint64

	// Field (0) 'Values'
	v.Values = ssz.ExtendUint64(v.Values, 6)
	for ii := 0; ii < 6; ii++ {
		v.Values[ii] = ssz.UnmarshallUint64(buf[0:48][ii*8 : (ii+1)*8])
	}

	// Offset (1) 'Values2'
	if o1 = ssz.ReadOffset(buf[48:52]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 < 52 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (1) 'Values2'
	{
		buf = tail[o1:]
		num, err := ssz.DivideInt2(len(buf), 4, 100)
		if err != nil {
			return err
		}
		v.Values2 = ssz.ExtendUint32(v.Values2, num)
		for ii := 0; ii < num; ii++ {
			v.Values2[ii] = ssz.UnmarshallUint32(buf[ii*4 : (ii+1)*4])
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the Vec object
func (v *Vec) SizeSSZ() (size int) {
	size = 52

	// Field (1) 'Values2'
	size += len(v.Values2) * 4

	return
}

// HashTreeRoot ssz hashes the Vec object
func (v *Vec) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(v)
}

// HashTreeRootWith ssz hashes the Vec object with a hasher
func (v *Vec) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Values'
	{
		if size := len(v.Values); size != 6 {
			err = ssz.ErrVectorLengthFn("Vec.Values", size, 6)
			return
		}
		subIndx := hh.Index()
		for _, i := range v.Values {
			hh.AppendUint64(i)
		}
		hh.Merkleize(subIndx)
	}

	// Field (1) 'Values2'
	{
		if size := len(v.Values2); size > 100 {
			err = ssz.ErrListTooBigFn("Vec.Values2", size, 100)
			return
		}
		subIndx := hh.Index()
		for _, i := range v.Values2 {
			hh.AppendUint32(i)
		}
		hh.FillUpTo32()
		numItems := uint64(len(v.Values2))
		hh.MerkleizeWithMixin(subIndx, numItems, ssz.CalculateLimit(100, numItems, 4))
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the Vec object
func (v *Vec) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(v)
}
