// Code generated by fastssz. DO NOT EDIT.
// Hash: 630165fff45d1be6db934447ebf7152569c492c7d0a9d927de980baf426c4638
// Version: 0.1.3
package testcases

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the Issue164 object
func (i *Issue164) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(i)
}

// MarshalSSZTo ssz marshals the Issue164 object to a target array
func (i *Issue164) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'A'
	dst = append(dst, i.A[:]...)

	return
}

// UnmarshalSSZ ssz unmarshals the Issue164 object
func (i *Issue164) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 20 {
		return ssz.ErrSize
	}

	// Field (0) 'A'
	copy(i.A[:], buf[0:20])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the Issue164 object
func (i *Issue164) SizeSSZ() (size int) {
	size = 20
	return
}

// HashTreeRoot ssz hashes the Issue164 object
func (i *Issue164) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(i)
}

// HashTreeRootWith ssz hashes the Issue164 object with a hasher
func (i *Issue164) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'A'
	hh.PutBytes(i.A[:])

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the Issue164 object
func (i *Issue164) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(i)
}
