// Code generated by fastssz. DO NOT EDIT.
// Hash: 21b78bac9121e91476779bed8a3475749aa30b687574d8441bafa8fe3c1e4621
// Version: 2.0.0
package testcases

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the Issue158 object
func (i *Issue158) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(i)
}

// MarshalSSZTo ssz marshals the Issue158 object to a target array
func (i *Issue158) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Field'
	if dst, err = i.Field.MarshalSSZTo(dst); err != nil {
		return
	}

	return
}

// UnmarshalSSZ ssz unmarshals the Issue158 object
func (i *Issue158) UnmarshalSSZ(buf []byte) error {
	return ssz.UnmarshalSSZ(i, buf)
}

// UnmarshalSSZTail unmarshals the Issue158 object and returns the remaining bufferº
func (i *Issue158) UnmarshalSSZTail(buf []byte) (rest []byte, err error) {
	size := len(buf)
	fixedSize := i.fixedSize()
	if size < fixedSize {
		return nil, ssz.ErrSize
	}

	// Field (0) 'Field'
	if buf, err = i.Field.UnmarshalSSZTail(buf); err != nil {
		return
	}

	return buf, nil
}

// fixedSize returns the fixed size of the Issue158 object
func (i *Issue158) fixedSize() int {
	return int(0)
}

// SizeSSZ returns the ssz encoded size in bytes for the Issue158 object
func (i *Issue158) SizeSSZ() (size int) {
	size = i.fixedSize()
	return
}

// HashTreeRoot ssz hashes the Issue158 object
func (i *Issue158) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(i)
}

// HashTreeRootWith ssz hashes the Issue158 object with a hasher
func (i *Issue158) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Field'
	if err = i.Field.HashTreeRootWith(hh); err != nil {
		return
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the Issue158 object
func (i *Issue158) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(i)
}
