// Code generated by fastssz. DO NOT EDIT.
// Hash: 750872c96c19534fb8b8f52e6a588fa19a3edac30cd15de2114e7c5a9a5963bb
// Version: 0.1.4
package testcases

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the Obj2 object
func (o *Obj2) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(o)
}

// MarshalSSZTo ssz marshals the Obj2 object to a target array
func (o *Obj2) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(4)

	// Offset (0) 'T1'
	dst = ssz.WriteOffset(dst, offset)

	// Field (0) 'T1'
	if size := len(o.T1); size > 1024 {
		err = ssz.ErrListTooBigFn("Obj2.T1", size, 1024)
		return
	}
	{
		offset = 4 * len(o.T1)
		for ii := 0; ii < len(o.T1); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += len(o.T1[ii])
		}
	}
	for ii := 0; ii < len(o.T1); ii++ {
		if size := len(o.T1[ii]); size > 256 {
			err = ssz.ErrBytesLengthFn("Obj2.T1[ii]", size, 256)
			return
		}
		dst = append(dst, o.T1[ii]...)
	}

	return
}

// UnmarshalSSZ ssz unmarshals the Obj2 object
func (o *Obj2) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 4 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'T1'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 != 4 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (0) 'T1'
	{
		buf = tail[o0:]
		num, err := ssz.DecodeDynamicLength(buf, 1024)
		if err != nil {
			return err
		}
		o.T1 = make([]Data, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if len(buf) > 256 {
				return ssz.ErrBytesLength
			}
			if cap(o.T1[indx]) == 0 {
				o.T1[indx] = make([]byte, 0, 256)
			}
			o.T1[indx] = append(o.T1[indx], buf...)
			return nil
		})
		if err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the Obj2 object
func (o *Obj2) SizeSSZ() (size int) {
	size = 4

	// Field (0) 'T1'
	for ii := 0; ii < len(o.T1); ii++ {
		size += 4
		size += len(o.T1[ii])
	}

	return
}

// HashTreeRoot ssz hashes the Obj2 object
func (o *Obj2) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(o)
}

// HashTreeRootWith ssz hashes the Obj2 object with a hasher
func (o *Obj2) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'T1'
	{
		subIndx := hh.Index()
		num := uint64(len(o.T1))
		if num > 1024 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range o.T1 {
			{
				elemIndx := hh.Index()
				byteLen := uint64(len(elem))
				if byteLen > 256 {
					err = ssz.ErrIncorrectListSize
					return
				}
				hh.AppendBytes32(elem)
				hh.MerkleizeWithMixin(elemIndx, byteLen, (256+31)/32)
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 1024)
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the Obj2 object
func (o *Obj2) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(o)
}
