// Code generated by fastssz. DO NOT EDIT.
// Hash: 836924a03d6ca2f956285e4009c8295f82267360d4f13c6a1df751e139e2b7e0
// Version: 2.0.0
package testcases

import (
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the Issue22 object
func (i *Issue22) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(i)
}

// MarshalSSZTo ssz marshals the Issue22 object to a target array
func (i *Issue22) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'Name'
	dst = ssz.MarshalValue(dst, i.Name)

	return
}

// UnmarshalSSZ ssz unmarshals the Issue22 object
func (i *Issue22) UnmarshalSSZ(buf []byte) error {
	return ssz.UnmarshalSSZ(i, buf)
}

// UnmarshalSSZTail unmarshals the Issue22 object and returns the remaining bufferº
func (i *Issue22) UnmarshalSSZTail(buf []byte) (rest []byte, err error) {
	size := len(buf)
	fixedSize := i.fixedSize()
	if size < fixedSize {
		return nil, ssz.ErrSize
	}

	// Field (0) 'Name'
	if err = ssz.IsValidBool(buf); err != nil {
		return
	}
	i.Name, buf = ssz.UnmarshallValue[bool](buf)

	return buf, nil
}

// fixedSize returns the fixed size of the Issue22 object
func (i *Issue22) fixedSize() int {
	return int(1)
}

// SizeSSZ returns the ssz encoded size in bytes for the Issue22 object
func (i *Issue22) SizeSSZ() (size int) {
	size = i.fixedSize()
	return
}

// HashTreeRoot ssz hashes the Issue22 object
func (i *Issue22) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(i)
}

// HashTreeRootWith ssz hashes the Issue22 object with a hasher
func (i *Issue22) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Name'
	hh.PutBool(i.Name)

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the Issue22 object
func (i *Issue22) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(i)
}
