// Code generated by fastssz. DO NOT EDIT.
// Hash: 66416148e8491c67660bb9075539e3e2f635024a31fd98e2d2ee34faf7dd1015
// Version: 0.1.3
package testcases

import (
	ssz "github.com/ferranbt/fastssz"
	"github.com/ferranbt/fastssz/sszgen/testcases/other"
)

// MarshalSSZ ssz marshals the Issue165 object
func (i *Issue165) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(i)
}

// MarshalSSZTo ssz marshals the Issue165 object to a target array
func (i *Issue165) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(4)

	// Offset (0) 'A'
	dst = ssz.WriteOffset(dst, offset)

	// Field (0) 'A'
	if size := len(i.A); size > 0 {
		err = ssz.ErrBytesLengthFn("Issue165.A", size, 0)
		return
	}
	dst = append(dst, i.A...)

	return
}

// UnmarshalSSZ ssz unmarshals the Issue165 object
func (i *Issue165) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 4 {
		return ssz.ErrSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'A'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 < 4 {
		return ssz.ErrInvalidVariableOffset
	}

	// Field (0) 'A'
	{
		buf = tail[o0:]
		if len(buf) > 0 {
			return ssz.ErrBytesLength
		}
		if cap(i.A) == 0 {
			i.A = other.Case4Bytes(make([]byte, 0, len(buf)))
		}
		i.A = append(i.A, buf...)
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the Issue165 object
func (i *Issue165) SizeSSZ() (size int) {
	size = 4

	// Field (0) 'A'
	size += len(i.A)

	return
}

// HashTreeRoot ssz hashes the Issue165 object
func (i *Issue165) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(i)
}

// HashTreeRootWith ssz hashes the Issue165 object with a hasher
func (i *Issue165) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'A'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(i.A))
		if byteLen > 0 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.Append(i.A)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (0+31)/32)
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the Issue165 object
func (i *Issue165) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(i)
}
