// Code generated by fastssz. DO NOT EDIT.
// Hash: 0d896adfcda7c1be16b727ee5ac72b5df56c28d4e67ad976864d94a0ae245935
// Version: 0.1.3
package testcases

import (
	ssz "github.com/ferranbt/fastssz"
	"github.com/ferranbt/fastssz/sszgen/testcases/other"
)

// MarshalSSZ ssz marshals the MyType object
func (m *MyType) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(m)
}

// MarshalSSZTo ssz marshals the MyType object to a target array
func (m *MyType) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(8)

	// Offset (0) 'MyField0'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(m.MyField0)

	// Offset (1) 'MyField1'
	dst = ssz.WriteOffset(dst, offset)

	// Field (0) 'MyField0'
	if size := len(m.MyField0); size > 0 {
		err = ssz.ErrBytesLengthFn("MyType.MyField0", size, 0)
		return
	}
	dst = append(dst, m.MyField0...)

	// Field (1) 'MyField1'
	if size := len(m.MyField1); size > 2 {
		err = ssz.ErrListTooBigFn("MyType.MyField1", size, 2)
		return
	}
	{
		offset = 4 * len(m.MyField1)
		for ii := 0; ii < len(m.MyField1); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += len(m.MyField1[ii])
		}
	}
	for ii := 0; ii < len(m.MyField1); ii++ {
		if size := len(m.MyField1[ii]); size > 2 {
			err = ssz.ErrBytesLengthFn("MyType.MyField1[ii]", size, 2)
			return
		}
		dst = append(dst, m.MyField1[ii]...)
	}

	return
}

// UnmarshalSSZ ssz unmarshals the MyType object
func (m *MyType) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 8 {
		return ssz.ErrSize
	}

	tail := buf
	var o0, o1 uint64

	// Offset (0) 'MyField0'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return ssz.ErrOffset
	}

	if o0 < 8 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (1) 'MyField1'
	if o1 = ssz.ReadOffset(buf[4:8]); o1 > size || o0 > o1 {
		return ssz.ErrOffset
	}

	// Field (0) 'MyField0'
	{
		buf = tail[o0:o1]
		if len(buf) > 0 {
			return ssz.ErrBytesLength
		}
		if cap(m.MyField0) == 0 {
			m.MyField0 = make([]byte, 0, len(buf))
		}
		m.MyField0 = append(m.MyField0, buf...)
	}

	// Field (1) 'MyField1'
	{
		buf = tail[o1:]
		num, err := ssz.DecodeDynamicLength(buf, 2)
		if err != nil {
			return err
		}
		m.MyField1 = make([]other.Case4Bytes, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if len(buf) > 2 {
				return ssz.ErrBytesLength
			}
			if cap(m.MyField1[indx]) == 0 {
				m.MyField1[indx] = other.Case4Bytes(make([]byte, 0, len(buf)))
			}
			m.MyField1[indx] = append(m.MyField1[indx], buf...)
			return nil
		})
		if err != nil {
			return err
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the MyType object
func (m *MyType) SizeSSZ() (size int) {
	size = 8

	// Field (0) 'MyField0'
	size += len(m.MyField0)

	// Field (1) 'MyField1'
	for ii := 0; ii < len(m.MyField1); ii++ {
		size += 4
		size += len(m.MyField1[ii])
	}

	return
}

// HashTreeRoot ssz hashes the MyType object
func (m *MyType) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(m)
}

// HashTreeRootWith ssz hashes the MyType object with a hasher
func (m *MyType) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'MyField0'
	{
		elemIndx := hh.Index()
		byteLen := uint64(len(m.MyField0))
		if byteLen > 0 {
			err = ssz.ErrIncorrectListSize
			return
		}
		hh.Append(m.MyField0)
		hh.MerkleizeWithMixin(elemIndx, byteLen, (0+31)/32)
	}

	// Field (1) 'MyField1'
	{
		subIndx := hh.Index()
		num := uint64(len(m.MyField1))
		if num > 2 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range m.MyField1 {
			{
				elemIndx := hh.Index()
				byteLen := uint64(len(elem))
				if byteLen > 2 {
					err = ssz.ErrIncorrectListSize
					return
				}
				hh.AppendBytes32(elem)
				hh.MerkleizeWithMixin(elemIndx, byteLen, (2+31)/32)
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 2)
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the MyType object
func (m *MyType) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(m)
}
