version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
    environment:
      FUZZ_TESTS: true
    steps:
      - checkout
      - run:
          command: |
            make get-spec-tests
      - run:
          command: |
            go test -v ./spectests/... -run TestSpec
            go test -v ./spectests/... -run TestErrorResponse
            go test -v ./spectests/... -run TestFuzzUnmarshalAppend