// Code generated by fastssz. DO NOT EDIT.
package spectests

import (
	"fmt"

	ssz "github.com/ferranbt/fastssz"
)

var (
	errDivideInt           = fmt.Errorf("incorrect int divide")
	errListTooBig          = fmt.Errorf("incorrect list size, too big")
	errMarshalDynamicBytes = fmt.Errorf("incorrect dynamic bytes marshalling")
	errMarshalFixedBytes   = fmt.Errorf("incorrect fixed bytes marshalling")
	errMarshalList         = fmt.Errorf("incorrect vector list")
	errMarshalVector       = fmt.Errorf("incorrect vector marshalling")
	errOffset              = fmt.Errorf("incorrect offset")
	errSize                = fmt.Errorf("incorrect size")
)

// Marshal ssz marshals the AggregateAndProof object
func (a *AggregateAndProof) Marshal() ([]byte, error) {
	buf := make([]byte, a.Size())
	return a.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the AggregateAndProof object to a target array
func (a *AggregateAndProof) MarshalTo(dst []byte) ([]byte, error) {
	var err error
	offset := int(108)

	// Field (0) 'Index'
	dst = ssz.MarshalUint64(dst, a.Index)

	// Offset (1) 'Aggregate'
	dst = ssz.WriteOffset(dst, offset)
	offset += a.Aggregate.Size()

	// Field (2) 'SelectionProof'
	if dst, err = ssz.MarshalFixedBytes(dst, a.SelectionProof, 96); err != nil {
		return nil, errMarshalFixedBytes
	}

	// Field (1) 'Aggregate'
	if dst, err = a.Aggregate.MarshalTo(dst); err != nil {
		return nil, err
	}

	return dst, err
}

// Unmarshal ssz unmarshals the AggregateAndProof object
func (a *AggregateAndProof) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 108 {
		return errSize
	}

	tail := buf
	var o1 uint64

	// Field (0) 'Index'
	a.Index = ssz.UnmarshallUint64(buf[0:8])

	// Offset (1) 'Aggregate'
	if o1 = ssz.ReadOffset(buf[8:12]); o1 > size {
		return errOffset
	}

	// Field (2) 'SelectionProof'
	a.SelectionProof = append(a.SelectionProof, buf[12:108]...)

	// Field (1) 'Aggregate'
	{
		buf = tail[o1:]
		if a.Aggregate == nil {
			a.Aggregate = new(Attestation)
		}
		if err = a.Aggregate.Unmarshal(buf); err != nil {
			return err
		}
	}
	return err
}

// Size returns the ssz encoded size in bytes for the AggregateAndProof object
func (a *AggregateAndProof) Size() (size int) {
	size = 108

	// Field (1) 'Aggregate'
	size += a.Aggregate.Size()

	return
}

// Marshal ssz marshals the Checkpoint object
func (c *Checkpoint) Marshal() ([]byte, error) {
	buf := make([]byte, c.Size())
	return c.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the Checkpoint object to a target array
func (c *Checkpoint) MarshalTo(dst []byte) ([]byte, error) {
	var err error

	// Field (0) 'Epoch'
	dst = ssz.MarshalUint64(dst, c.Epoch)

	// Field (1) 'Root'
	if dst, err = ssz.MarshalFixedBytes(dst, c.Root, 32); err != nil {
		return nil, errMarshalFixedBytes
	}

	return dst, err
}

// Unmarshal ssz unmarshals the Checkpoint object
func (c *Checkpoint) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 40 {
		return errSize
	}

	// Field (0) 'Epoch'
	c.Epoch = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'Root'
	c.Root = append(c.Root, buf[8:40]...)

	return err
}

// Size returns the ssz encoded size in bytes for the Checkpoint object
func (c *Checkpoint) Size() (size int) {
	size = 40
	return
}

// Marshal ssz marshals the AttestationData object
func (a *AttestationData) Marshal() ([]byte, error) {
	buf := make([]byte, a.Size())
	return a.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the AttestationData object to a target array
func (a *AttestationData) MarshalTo(dst []byte) ([]byte, error) {
	var err error

	// Field (0) 'Slot'
	dst = ssz.MarshalUint64(dst, a.Slot)

	// Field (1) 'Index'
	dst = ssz.MarshalUint64(dst, a.Index)

	// Field (2) 'BeaconBlockHash'
	if dst, err = ssz.MarshalFixedBytes(dst, a.BeaconBlockHash, 32); err != nil {
		return nil, errMarshalFixedBytes
	}

	// Field (3) 'Source'
	if dst, err = a.Source.MarshalTo(dst); err != nil {
		return nil, err
	}

	// Field (4) 'Target'
	if dst, err = a.Target.MarshalTo(dst); err != nil {
		return nil, err
	}

	return dst, err
}

// Unmarshal ssz unmarshals the AttestationData object
func (a *AttestationData) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 128 {
		return errSize
	}

	// Field (0) 'Slot'
	a.Slot = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'Index'
	a.Index = ssz.UnmarshallUint64(buf[8:16])

	// Field (2) 'BeaconBlockHash'
	a.BeaconBlockHash = append(a.BeaconBlockHash, buf[16:48]...)

	// Field (3) 'Source'
	if a.Source == nil {
		a.Source = new(Checkpoint)
	}
	if err = a.Source.Unmarshal(buf[48:88]); err != nil {
		return err
	}

	// Field (4) 'Target'
	if a.Target == nil {
		a.Target = new(Checkpoint)
	}
	if err = a.Target.Unmarshal(buf[88:128]); err != nil {
		return err
	}

	return err
}

// Size returns the ssz encoded size in bytes for the AttestationData object
func (a *AttestationData) Size() (size int) {
	size = 128
	return
}

// Marshal ssz marshals the Attestation object
func (a *Attestation) Marshal() ([]byte, error) {
	buf := make([]byte, a.Size())
	return a.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the Attestation object to a target array
func (a *Attestation) MarshalTo(dst []byte) ([]byte, error) {
	var err error
	offset := int(228)

	// Offset (0) 'AggregationBits'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(a.AggregationBits)

	// Field (1) 'Data'
	if dst, err = a.Data.MarshalTo(dst); err != nil {
		return nil, err
	}

	// Field (2) 'Signature'
	if dst, err = ssz.MarshalFixedBytes(dst, a.Signature, 96); err != nil {
		return nil, errMarshalFixedBytes
	}

	// Field (0) 'AggregationBits'
	dst = append(dst, a.AggregationBits...)

	return dst, err
}

// Unmarshal ssz unmarshals the Attestation object
func (a *Attestation) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 228 {
		return errSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'AggregationBits'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return errOffset
	}

	// Field (1) 'Data'
	if a.Data == nil {
		a.Data = new(AttestationData)
	}
	if err = a.Data.Unmarshal(buf[4:132]); err != nil {
		return err
	}

	// Field (2) 'Signature'
	a.Signature = append(a.Signature, buf[132:228]...)

	// Field (0) 'AggregationBits'
	{
		buf = tail[o0:]
		a.AggregationBits = append(a.AggregationBits, buf...)
	}
	return err
}

// Size returns the ssz encoded size in bytes for the Attestation object
func (a *Attestation) Size() (size int) {
	size = 228

	// Field (0) 'AggregationBits'
	size += len(a.AggregationBits)

	return
}

// Marshal ssz marshals the DepositData object
func (d *DepositData) Marshal() ([]byte, error) {
	buf := make([]byte, d.Size())
	return d.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the DepositData object to a target array
func (d *DepositData) MarshalTo(dst []byte) ([]byte, error) {
	var err error

	// Field (0) 'Pubkey'
	if dst, err = ssz.MarshalFixedBytes(dst, d.Pubkey, 48); err != nil {
		return nil, errMarshalFixedBytes
	}

	// Field (1) 'WithdrawalCredentials'
	if dst, err = ssz.MarshalFixedBytes(dst, d.WithdrawalCredentials, 32); err != nil {
		return nil, errMarshalFixedBytes
	}

	// Field (2) 'Amount'
	dst = ssz.MarshalUint64(dst, d.Amount)

	// Field (3) 'Signature'
	if dst, err = ssz.MarshalFixedBytes(dst, d.Signature, 96); err != nil {
		return nil, errMarshalFixedBytes
	}

	return dst, err
}

// Unmarshal ssz unmarshals the DepositData object
func (d *DepositData) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 184 {
		return errSize
	}

	// Field (0) 'Pubkey'
	d.Pubkey = append(d.Pubkey, buf[0:48]...)

	// Field (1) 'WithdrawalCredentials'
	d.WithdrawalCredentials = append(d.WithdrawalCredentials, buf[48:80]...)

	// Field (2) 'Amount'
	d.Amount = ssz.UnmarshallUint64(buf[80:88])

	// Field (3) 'Signature'
	d.Signature = append(d.Signature, buf[88:184]...)

	return err
}

// Size returns the ssz encoded size in bytes for the DepositData object
func (d *DepositData) Size() (size int) {
	size = 184
	return
}

// Marshal ssz marshals the Deposit object
func (d *Deposit) Marshal() ([]byte, error) {
	buf := make([]byte, d.Size())
	return d.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the Deposit object to a target array
func (d *Deposit) MarshalTo(dst []byte) ([]byte, error) {
	var err error

	// Field (0) 'Proof'
	if len(d.Proof) != 33 {
		return nil, errMarshalVector
	}
	for ii := 0; ii < 33; ii++ {
		if dst, err = ssz.MarshalFixedBytes(dst, d.Proof[ii], 32); err != nil {
			return nil, errMarshalFixedBytes
		}
	}

	// Field (1) 'Data'
	if dst, err = d.Data.MarshalTo(dst); err != nil {
		return nil, err
	}

	return dst, err
}

// Unmarshal ssz unmarshals the Deposit object
func (d *Deposit) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 1240 {
		return errSize
	}

	// Field (0) 'Proof'
	d.Proof = make([][]byte, 33)
	for ii := 0; ii < 33; ii++ {
		d.Proof[ii] = append(d.Proof[ii], buf[0:1056][ii*32:(ii+1)*32]...)
	}

	// Field (1) 'Data'
	if d.Data == nil {
		d.Data = new(DepositData)
	}
	if err = d.Data.Unmarshal(buf[1056:1240]); err != nil {
		return err
	}

	return err
}

// Size returns the ssz encoded size in bytes for the Deposit object
func (d *Deposit) Size() (size int) {
	size = 1240
	return
}

// Marshal ssz marshals the DepositMessage object
func (d *DepositMessage) Marshal() ([]byte, error) {
	buf := make([]byte, d.Size())
	return d.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the DepositMessage object to a target array
func (d *DepositMessage) MarshalTo(dst []byte) ([]byte, error) {
	var err error

	// Field (0) 'Pubkey'
	if dst, err = ssz.MarshalFixedBytes(dst, d.Pubkey, 48); err != nil {
		return nil, errMarshalFixedBytes
	}

	// Field (1) 'WithdrawalCredentials'
	if dst, err = ssz.MarshalFixedBytes(dst, d.WithdrawalCredentials, 32); err != nil {
		return nil, errMarshalFixedBytes
	}

	// Field (2) 'Amount'
	dst = ssz.MarshalUint64(dst, d.Amount)

	return dst, err
}

// Unmarshal ssz unmarshals the DepositMessage object
func (d *DepositMessage) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 88 {
		return errSize
	}

	// Field (0) 'Pubkey'
	d.Pubkey = append(d.Pubkey, buf[0:48]...)

	// Field (1) 'WithdrawalCredentials'
	d.WithdrawalCredentials = append(d.WithdrawalCredentials, buf[48:80]...)

	// Field (2) 'Amount'
	d.Amount = ssz.UnmarshallUint64(buf[80:88])

	return err
}

// Size returns the ssz encoded size in bytes for the DepositMessage object
func (d *DepositMessage) Size() (size int) {
	size = 88
	return
}

// Marshal ssz marshals the IndexedAttestation object
func (i *IndexedAttestation) Marshal() ([]byte, error) {
	buf := make([]byte, i.Size())
	return i.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the IndexedAttestation object to a target array
func (i *IndexedAttestation) MarshalTo(dst []byte) ([]byte, error) {
	var err error
	offset := int(228)

	// Offset (0) 'AttestationIndices'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(i.AttestationIndices) * 8

	// Field (1) 'Data'
	if dst, err = i.Data.MarshalTo(dst); err != nil {
		return nil, err
	}

	// Field (2) 'Signature'
	if dst, err = ssz.MarshalFixedBytes(dst, i.Signature, 96); err != nil {
		return nil, errMarshalFixedBytes
	}

	// Field (0) 'AttestationIndices'
	if len(i.AttestationIndices) > 2048 {
		return nil, errMarshalList
	}
	for ii := 0; ii < len(i.AttestationIndices); ii++ {
		dst = ssz.MarshalUint64(dst, i.AttestationIndices[ii])
	}

	return dst, err
}

// Unmarshal ssz unmarshals the IndexedAttestation object
func (i *IndexedAttestation) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 228 {
		return errSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'AttestationIndices'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return errOffset
	}

	// Field (1) 'Data'
	if i.Data == nil {
		i.Data = new(AttestationData)
	}
	if err = i.Data.Unmarshal(buf[4:132]); err != nil {
		return err
	}

	// Field (2) 'Signature'
	i.Signature = append(i.Signature, buf[132:228]...)

	// Field (0) 'AttestationIndices'
	{
		buf = tail[o0:]
		num, ok := ssz.DivideInt(len(buf), 8)
		if !ok {
			return errDivideInt
		}
		if num > 2048 {
			return errListTooBig
		}
		i.AttestationIndices = ssz.ExtendUint64(i.AttestationIndices, num)
		for ii := 0; ii < num; ii++ {
			i.AttestationIndices[ii] = ssz.UnmarshallUint64(buf[ii*8 : (ii+1)*8])
		}
	}
	return err
}

// Size returns the ssz encoded size in bytes for the IndexedAttestation object
func (i *IndexedAttestation) Size() (size int) {
	size = 228

	// Field (0) 'AttestationIndices'
	size += len(i.AttestationIndices) * 8

	return
}

// Marshal ssz marshals the PendingAttestation object
func (p *PendingAttestation) Marshal() ([]byte, error) {
	buf := make([]byte, p.Size())
	return p.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the PendingAttestation object to a target array
func (p *PendingAttestation) MarshalTo(dst []byte) ([]byte, error) {
	var err error
	offset := int(148)

	// Offset (0) 'AggregationBits'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(p.AggregationBits)

	// Field (1) 'Data'
	if dst, err = p.Data.MarshalTo(dst); err != nil {
		return nil, err
	}

	// Field (2) 'InclusionDelay'
	dst = ssz.MarshalUint64(dst, p.InclusionDelay)

	// Field (3) 'ProposerIndex'
	dst = ssz.MarshalUint64(dst, p.ProposerIndex)

	// Field (0) 'AggregationBits'
	if len(p.AggregationBits) > 2048 {
		return nil, errMarshalDynamicBytes
	}
	dst = append(dst, p.AggregationBits...)

	return dst, err
}

// Unmarshal ssz unmarshals the PendingAttestation object
func (p *PendingAttestation) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 148 {
		return errSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'AggregationBits'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return errOffset
	}

	// Field (1) 'Data'
	if p.Data == nil {
		p.Data = new(AttestationData)
	}
	if err = p.Data.Unmarshal(buf[4:132]); err != nil {
		return err
	}

	// Field (2) 'InclusionDelay'
	p.InclusionDelay = ssz.UnmarshallUint64(buf[132:140])

	// Field (3) 'ProposerIndex'
	p.ProposerIndex = ssz.UnmarshallUint64(buf[140:148])

	// Field (0) 'AggregationBits'
	{
		buf = tail[o0:]
		p.AggregationBits = append(p.AggregationBits, buf...)
	}
	return err
}

// Size returns the ssz encoded size in bytes for the PendingAttestation object
func (p *PendingAttestation) Size() (size int) {
	size = 148

	// Field (0) 'AggregationBits'
	size += len(p.AggregationBits)

	return
}

// Marshal ssz marshals the Fork object
func (f *Fork) Marshal() ([]byte, error) {
	buf := make([]byte, f.Size())
	return f.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the Fork object to a target array
func (f *Fork) MarshalTo(dst []byte) ([]byte, error) {
	var err error

	// Field (0) 'PreviousVersion'
	if dst, err = ssz.MarshalFixedBytes(dst, f.PreviousVersion, 4); err != nil {
		return nil, errMarshalFixedBytes
	}

	// Field (1) 'CurrentVersion'
	if dst, err = ssz.MarshalFixedBytes(dst, f.CurrentVersion, 4); err != nil {
		return nil, errMarshalFixedBytes
	}

	// Field (2) 'Epoch'
	dst = ssz.MarshalUint64(dst, f.Epoch)

	return dst, err
}

// Unmarshal ssz unmarshals the Fork object
func (f *Fork) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 16 {
		return errSize
	}

	// Field (0) 'PreviousVersion'
	f.PreviousVersion = append(f.PreviousVersion, buf[0:4]...)

	// Field (1) 'CurrentVersion'
	f.CurrentVersion = append(f.CurrentVersion, buf[4:8]...)

	// Field (2) 'Epoch'
	f.Epoch = ssz.UnmarshallUint64(buf[8:16])

	return err
}

// Size returns the ssz encoded size in bytes for the Fork object
func (f *Fork) Size() (size int) {
	size = 16
	return
}

// Marshal ssz marshals the Validator object
func (v *Validator) Marshal() ([]byte, error) {
	buf := make([]byte, v.Size())
	return v.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the Validator object to a target array
func (v *Validator) MarshalTo(dst []byte) ([]byte, error) {
	var err error

	// Field (0) 'Pubkey'
	if dst, err = ssz.MarshalFixedBytes(dst, v.Pubkey, 48); err != nil {
		return nil, errMarshalFixedBytes
	}

	// Field (1) 'WithdrawalCredentials'
	if dst, err = ssz.MarshalFixedBytes(dst, v.WithdrawalCredentials, 32); err != nil {
		return nil, errMarshalFixedBytes
	}

	// Field (2) 'EffectiveBalance'
	dst = ssz.MarshalUint64(dst, v.EffectiveBalance)

	// Field (3) 'Slashed'
	dst = ssz.MarshalBool(dst, v.Slashed)

	// Field (4) 'ActivationEligibilityEpoch'
	dst = ssz.MarshalUint64(dst, v.ActivationEligibilityEpoch)

	// Field (5) 'ActivationEpoch'
	dst = ssz.MarshalUint64(dst, v.ActivationEpoch)

	// Field (6) 'ExitEpoch'
	dst = ssz.MarshalUint64(dst, v.ExitEpoch)

	// Field (7) 'WithdrawableEpoch'
	dst = ssz.MarshalUint64(dst, v.WithdrawableEpoch)

	return dst, err
}

// Unmarshal ssz unmarshals the Validator object
func (v *Validator) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 121 {
		return errSize
	}

	// Field (0) 'Pubkey'
	v.Pubkey = append(v.Pubkey, buf[0:48]...)

	// Field (1) 'WithdrawalCredentials'
	v.WithdrawalCredentials = append(v.WithdrawalCredentials, buf[48:80]...)

	// Field (2) 'EffectiveBalance'
	v.EffectiveBalance = ssz.UnmarshallUint64(buf[80:88])

	// Field (3) 'Slashed'
	v.Slashed = ssz.UnmarshalBool(buf[88:89])

	// Field (4) 'ActivationEligibilityEpoch'
	v.ActivationEligibilityEpoch = ssz.UnmarshallUint64(buf[89:97])

	// Field (5) 'ActivationEpoch'
	v.ActivationEpoch = ssz.UnmarshallUint64(buf[97:105])

	// Field (6) 'ExitEpoch'
	v.ExitEpoch = ssz.UnmarshallUint64(buf[105:113])

	// Field (7) 'WithdrawableEpoch'
	v.WithdrawableEpoch = ssz.UnmarshallUint64(buf[113:121])

	return err
}

// Size returns the ssz encoded size in bytes for the Validator object
func (v *Validator) Size() (size int) {
	size = 121
	return
}

// Marshal ssz marshals the VoluntaryExit object
func (v *VoluntaryExit) Marshal() ([]byte, error) {
	buf := make([]byte, v.Size())
	return v.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the VoluntaryExit object to a target array
func (v *VoluntaryExit) MarshalTo(dst []byte) ([]byte, error) {
	var err error

	// Field (0) 'Epoch'
	dst = ssz.MarshalUint64(dst, v.Epoch)

	// Field (1) 'ValidatorIndex'
	dst = ssz.MarshalUint64(dst, v.ValidatorIndex)

	return dst, err
}

// Unmarshal ssz unmarshals the VoluntaryExit object
func (v *VoluntaryExit) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 16 {
		return errSize
	}

	// Field (0) 'Epoch'
	v.Epoch = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'ValidatorIndex'
	v.ValidatorIndex = ssz.UnmarshallUint64(buf[8:16])

	return err
}

// Size returns the ssz encoded size in bytes for the VoluntaryExit object
func (v *VoluntaryExit) Size() (size int) {
	size = 16
	return
}

// Marshal ssz marshals the SignedVoluntaryExit object
func (s *SignedVoluntaryExit) Marshal() ([]byte, error) {
	buf := make([]byte, s.Size())
	return s.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the SignedVoluntaryExit object to a target array
func (s *SignedVoluntaryExit) MarshalTo(dst []byte) ([]byte, error) {
	var err error

	// Field (0) 'Exit'
	if dst, err = s.Exit.MarshalTo(dst); err != nil {
		return nil, err
	}

	// Field (1) 'Signature'
	if dst, err = ssz.MarshalFixedBytes(dst, s.Signature, 96); err != nil {
		return nil, errMarshalFixedBytes
	}

	return dst, err
}

// Unmarshal ssz unmarshals the SignedVoluntaryExit object
func (s *SignedVoluntaryExit) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 112 {
		return errSize
	}

	// Field (0) 'Exit'
	if s.Exit == nil {
		s.Exit = new(VoluntaryExit)
	}
	if err = s.Exit.Unmarshal(buf[0:16]); err != nil {
		return err
	}

	// Field (1) 'Signature'
	s.Signature = append(s.Signature, buf[16:112]...)

	return err
}

// Size returns the ssz encoded size in bytes for the SignedVoluntaryExit object
func (s *SignedVoluntaryExit) Size() (size int) {
	size = 112
	return
}

// Marshal ssz marshals the Eth1Block object
func (e *Eth1Block) Marshal() ([]byte, error) {
	buf := make([]byte, e.Size())
	return e.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the Eth1Block object to a target array
func (e *Eth1Block) MarshalTo(dst []byte) ([]byte, error) {
	var err error

	// Field (0) 'Timestamp'
	dst = ssz.MarshalUint64(dst, e.Timestamp)

	return dst, err
}

// Unmarshal ssz unmarshals the Eth1Block object
func (e *Eth1Block) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 8 {
		return errSize
	}

	// Field (0) 'Timestamp'
	e.Timestamp = ssz.UnmarshallUint64(buf[0:8])

	return err
}

// Size returns the ssz encoded size in bytes for the Eth1Block object
func (e *Eth1Block) Size() (size int) {
	size = 8
	return
}

// Marshal ssz marshals the Eth1Data object
func (e *Eth1Data) Marshal() ([]byte, error) {
	buf := make([]byte, e.Size())
	return e.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the Eth1Data object to a target array
func (e *Eth1Data) MarshalTo(dst []byte) ([]byte, error) {
	var err error

	// Field (0) 'DepositRoot'
	if dst, err = ssz.MarshalFixedBytes(dst, e.DepositRoot, 32); err != nil {
		return nil, errMarshalFixedBytes
	}

	// Field (1) 'DepositCount'
	dst = ssz.MarshalUint64(dst, e.DepositCount)

	// Field (2) 'BlockHash'
	if dst, err = ssz.MarshalFixedBytes(dst, e.BlockHash, 32); err != nil {
		return nil, errMarshalFixedBytes
	}

	return dst, err
}

// Unmarshal ssz unmarshals the Eth1Data object
func (e *Eth1Data) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 72 {
		return errSize
	}

	// Field (0) 'DepositRoot'
	e.DepositRoot = append(e.DepositRoot, buf[0:32]...)

	// Field (1) 'DepositCount'
	e.DepositCount = ssz.UnmarshallUint64(buf[32:40])

	// Field (2) 'BlockHash'
	e.BlockHash = append(e.BlockHash, buf[40:72]...)

	return err
}

// Size returns the ssz encoded size in bytes for the Eth1Data object
func (e *Eth1Data) Size() (size int) {
	size = 72
	return
}

// Marshal ssz marshals the SigningRoot object
func (s *SigningRoot) Marshal() ([]byte, error) {
	buf := make([]byte, s.Size())
	return s.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the SigningRoot object to a target array
func (s *SigningRoot) MarshalTo(dst []byte) ([]byte, error) {
	var err error

	// Field (0) 'ObjectRoot'
	if dst, err = ssz.MarshalFixedBytes(dst, s.ObjectRoot, 32); err != nil {
		return nil, errMarshalFixedBytes
	}

	// Field (1) 'Domain'
	if dst, err = ssz.MarshalFixedBytes(dst, s.Domain, 8); err != nil {
		return nil, errMarshalFixedBytes
	}

	return dst, err
}

// Unmarshal ssz unmarshals the SigningRoot object
func (s *SigningRoot) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 40 {
		return errSize
	}

	// Field (0) 'ObjectRoot'
	s.ObjectRoot = append(s.ObjectRoot, buf[0:32]...)

	// Field (1) 'Domain'
	s.Domain = append(s.Domain, buf[32:40]...)

	return err
}

// Size returns the ssz encoded size in bytes for the SigningRoot object
func (s *SigningRoot) Size() (size int) {
	size = 40
	return
}

// Marshal ssz marshals the HistoricalBatch object
func (h *HistoricalBatch) Marshal() ([]byte, error) {
	buf := make([]byte, h.Size())
	return h.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the HistoricalBatch object to a target array
func (h *HistoricalBatch) MarshalTo(dst []byte) ([]byte, error) {
	var err error

	// Field (0) 'BlockRoots'
	if len(h.BlockRoots) != 64 {
		return nil, errMarshalVector
	}
	for ii := 0; ii < 64; ii++ {
		if dst, err = ssz.MarshalFixedBytes(dst, h.BlockRoots[ii], 32); err != nil {
			return nil, errMarshalFixedBytes
		}
	}

	// Field (1) 'StateRoots'
	if len(h.StateRoots) != 64 {
		return nil, errMarshalVector
	}
	for ii := 0; ii < 64; ii++ {
		if dst, err = ssz.MarshalFixedBytes(dst, h.StateRoots[ii], 32); err != nil {
			return nil, errMarshalFixedBytes
		}
	}

	return dst, err
}

// Unmarshal ssz unmarshals the HistoricalBatch object
func (h *HistoricalBatch) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 4096 {
		return errSize
	}

	// Field (0) 'BlockRoots'
	h.BlockRoots = make([][]byte, 64)
	for ii := 0; ii < 64; ii++ {
		h.BlockRoots[ii] = append(h.BlockRoots[ii], buf[0:2048][ii*32:(ii+1)*32]...)
	}

	// Field (1) 'StateRoots'
	h.StateRoots = make([][]byte, 64)
	for ii := 0; ii < 64; ii++ {
		h.StateRoots[ii] = append(h.StateRoots[ii], buf[2048:4096][ii*32:(ii+1)*32]...)
	}

	return err
}

// Size returns the ssz encoded size in bytes for the HistoricalBatch object
func (h *HistoricalBatch) Size() (size int) {
	size = 4096
	return
}

// Marshal ssz marshals the ProposerSlashing object
func (p *ProposerSlashing) Marshal() ([]byte, error) {
	buf := make([]byte, p.Size())
	return p.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the ProposerSlashing object to a target array
func (p *ProposerSlashing) MarshalTo(dst []byte) ([]byte, error) {
	var err error

	// Field (0) 'ProposerIndex'
	dst = ssz.MarshalUint64(dst, p.ProposerIndex)

	// Field (1) 'Header1'
	if dst, err = p.Header1.MarshalTo(dst); err != nil {
		return nil, err
	}

	// Field (2) 'Header2'
	if dst, err = p.Header2.MarshalTo(dst); err != nil {
		return nil, err
	}

	return dst, err
}

// Unmarshal ssz unmarshals the ProposerSlashing object
func (p *ProposerSlashing) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 408 {
		return errSize
	}

	// Field (0) 'ProposerIndex'
	p.ProposerIndex = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'Header1'
	if p.Header1 == nil {
		p.Header1 = new(SignedBeaconBlockHeader)
	}
	if err = p.Header1.Unmarshal(buf[8:208]); err != nil {
		return err
	}

	// Field (2) 'Header2'
	if p.Header2 == nil {
		p.Header2 = new(SignedBeaconBlockHeader)
	}
	if err = p.Header2.Unmarshal(buf[208:408]); err != nil {
		return err
	}

	return err
}

// Size returns the ssz encoded size in bytes for the ProposerSlashing object
func (p *ProposerSlashing) Size() (size int) {
	size = 408
	return
}

// Marshal ssz marshals the AttesterSlashing object
func (a *AttesterSlashing) Marshal() ([]byte, error) {
	buf := make([]byte, a.Size())
	return a.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the AttesterSlashing object to a target array
func (a *AttesterSlashing) MarshalTo(dst []byte) ([]byte, error) {
	var err error
	offset := int(8)

	// Offset (0) 'Attestation1'
	dst = ssz.WriteOffset(dst, offset)
	offset += a.Attestation1.Size()

	// Offset (1) 'Attestation2'
	dst = ssz.WriteOffset(dst, offset)
	offset += a.Attestation2.Size()

	// Field (0) 'Attestation1'
	if dst, err = a.Attestation1.MarshalTo(dst); err != nil {
		return nil, err
	}

	// Field (1) 'Attestation2'
	if dst, err = a.Attestation2.MarshalTo(dst); err != nil {
		return nil, err
	}

	return dst, err
}

// Unmarshal ssz unmarshals the AttesterSlashing object
func (a *AttesterSlashing) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 8 {
		return errSize
	}

	tail := buf
	var o0, o1 uint64

	// Offset (0) 'Attestation1'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return errOffset
	}

	// Offset (1) 'Attestation2'
	if o1 = ssz.ReadOffset(buf[4:8]); o1 > size || o0 > o1 {
		return errOffset
	}

	// Field (0) 'Attestation1'
	{
		buf = tail[o0:o1]
		if a.Attestation1 == nil {
			a.Attestation1 = new(IndexedAttestation)
		}
		if err = a.Attestation1.Unmarshal(buf); err != nil {
			return err
		}
	}

	// Field (1) 'Attestation2'
	{
		buf = tail[o1:]
		if a.Attestation2 == nil {
			a.Attestation2 = new(IndexedAttestation)
		}
		if err = a.Attestation2.Unmarshal(buf); err != nil {
			return err
		}
	}
	return err
}

// Size returns the ssz encoded size in bytes for the AttesterSlashing object
func (a *AttesterSlashing) Size() (size int) {
	size = 8

	// Field (0) 'Attestation1'
	size += a.Attestation1.Size()

	// Field (1) 'Attestation2'
	size += a.Attestation2.Size()

	return
}

// Marshal ssz marshals the BeaconState object
func (b *BeaconState) Marshal() ([]byte, error) {
	buf := make([]byte, b.Size())
	return b.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the BeaconState object to a target array
func (b *BeaconState) MarshalTo(dst []byte) ([]byte, error) {
	var err error
	offset := int(7017)

	// Field (0) 'GenesisTime'
	dst = ssz.MarshalUint64(dst, b.GenesisTime)

	// Field (1) 'Slot'
	dst = ssz.MarshalUint64(dst, b.Slot)

	// Field (2) 'Fork'
	if dst, err = b.Fork.MarshalTo(dst); err != nil {
		return nil, err
	}

	// Field (3) 'LatestBlockHeader'
	if dst, err = b.LatestBlockHeader.MarshalTo(dst); err != nil {
		return nil, err
	}

	// Field (4) 'BlockRoots'
	if len(b.BlockRoots) != 64 {
		return nil, errMarshalVector
	}
	for ii := 0; ii < 64; ii++ {
		if dst, err = ssz.MarshalFixedBytes(dst, b.BlockRoots[ii], 32); err != nil {
			return nil, errMarshalFixedBytes
		}
	}

	// Field (5) 'StateRoots'
	if len(b.StateRoots) != 64 {
		return nil, errMarshalVector
	}
	for ii := 0; ii < 64; ii++ {
		if dst, err = ssz.MarshalFixedBytes(dst, b.StateRoots[ii], 32); err != nil {
			return nil, errMarshalFixedBytes
		}
	}

	// Offset (6) 'HistoricalRoots'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.HistoricalRoots) * 32

	// Field (7) 'Eth1Data'
	if dst, err = b.Eth1Data.MarshalTo(dst); err != nil {
		return nil, err
	}

	// Offset (8) 'Eth1DataVotes'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.Eth1DataVotes) * 72

	// Field (9) 'Eth1DepositIndex'
	dst = ssz.MarshalUint64(dst, b.Eth1DepositIndex)

	// Offset (10) 'Validators'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.Validators) * 121

	// Offset (11) 'Balances'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.Balances) * 8

	// Field (12) 'RandaoMixes'
	if len(b.RandaoMixes) != 64 {
		return nil, errMarshalVector
	}
	for ii := 0; ii < 64; ii++ {
		if dst, err = ssz.MarshalFixedBytes(dst, b.RandaoMixes[ii], 32); err != nil {
			return nil, errMarshalFixedBytes
		}
	}

	// Field (13) 'Slashings'
	if len(b.Slashings) != 64 {
		return nil, errMarshalVector
	}
	for ii := 0; ii < 64; ii++ {
		dst = ssz.MarshalUint64(dst, b.Slashings[ii])
	}

	// Offset (14) 'PreviousEpochAttestations'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(b.PreviousEpochAttestations); ii++ {
		offset += 4
		offset += b.PreviousEpochAttestations[ii].Size()
	}

	// Offset (15) 'CurrentEpochAttestations'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(b.CurrentEpochAttestations); ii++ {
		offset += 4
		offset += b.CurrentEpochAttestations[ii].Size()
	}

	// Field (16) 'JustificationBits'
	if dst, err = ssz.MarshalFixedBytes(dst, b.JustificationBits, 1); err != nil {
		return nil, errMarshalFixedBytes
	}

	// Field (17) 'PreviousJustifiedCheckpoint'
	if dst, err = b.PreviousJustifiedCheckpoint.MarshalTo(dst); err != nil {
		return nil, err
	}

	// Field (18) 'CurrentJustifiedCheckpoint'
	if dst, err = b.CurrentJustifiedCheckpoint.MarshalTo(dst); err != nil {
		return nil, err
	}

	// Field (19) 'FinalizedCheckpoint'
	if dst, err = b.FinalizedCheckpoint.MarshalTo(dst); err != nil {
		return nil, err
	}

	// Field (6) 'HistoricalRoots'
	if len(b.HistoricalRoots) > 16777216 {
		return nil, errMarshalList
	}
	for ii := 0; ii < len(b.HistoricalRoots); ii++ {
		if dst, err = ssz.MarshalFixedBytes(dst, b.HistoricalRoots[ii], 32); err != nil {
			return nil, errMarshalFixedBytes
		}
	}

	// Field (8) 'Eth1DataVotes'
	if len(b.Eth1DataVotes) > 1024 {
		return nil, errMarshalList
	}
	for ii := 0; ii < len(b.Eth1DataVotes); ii++ {
		if dst, err = b.Eth1DataVotes[ii].MarshalTo(dst); err != nil {
			return nil, err
		}
	}

	// Field (10) 'Validators'
	if len(b.Validators) > 1099511627776 {
		return nil, errMarshalList
	}
	for ii := 0; ii < len(b.Validators); ii++ {
		if dst, err = b.Validators[ii].MarshalTo(dst); err != nil {
			return nil, err
		}
	}

	// Field (11) 'Balances'
	if len(b.Balances) > 1099511627776 {
		return nil, errMarshalList
	}
	for ii := 0; ii < len(b.Balances); ii++ {
		dst = ssz.MarshalUint64(dst, b.Balances[ii])
	}

	// Field (14) 'PreviousEpochAttestations'
	if len(b.PreviousEpochAttestations) > 4096 {
		return nil, errMarshalList
	}
	{
		offset = 4 * len(b.PreviousEpochAttestations)
		for ii := 0; ii < len(b.PreviousEpochAttestations); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += b.PreviousEpochAttestations[ii].Size()
		}
	}
	for ii := 0; ii < len(b.PreviousEpochAttestations); ii++ {
		if dst, err = b.PreviousEpochAttestations[ii].MarshalTo(dst); err != nil {
			return nil, err
		}
	}

	// Field (15) 'CurrentEpochAttestations'
	if len(b.CurrentEpochAttestations) > 4096 {
		return nil, errMarshalList
	}
	{
		offset = 4 * len(b.CurrentEpochAttestations)
		for ii := 0; ii < len(b.CurrentEpochAttestations); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += b.CurrentEpochAttestations[ii].Size()
		}
	}
	for ii := 0; ii < len(b.CurrentEpochAttestations); ii++ {
		if dst, err = b.CurrentEpochAttestations[ii].MarshalTo(dst); err != nil {
			return nil, err
		}
	}

	return dst, err
}

// Unmarshal ssz unmarshals the BeaconState object
func (b *BeaconState) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 7017 {
		return errSize
	}

	tail := buf
	var o6, o8, o10, o11, o14, o15 uint64

	// Field (0) 'GenesisTime'
	b.GenesisTime = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'Slot'
	b.Slot = ssz.UnmarshallUint64(buf[8:16])

	// Field (2) 'Fork'
	if b.Fork == nil {
		b.Fork = new(Fork)
	}
	if err = b.Fork.Unmarshal(buf[16:32]); err != nil {
		return err
	}

	// Field (3) 'LatestBlockHeader'
	if b.LatestBlockHeader == nil {
		b.LatestBlockHeader = new(BeaconBlockHeader)
	}
	if err = b.LatestBlockHeader.Unmarshal(buf[32:136]); err != nil {
		return err
	}

	// Field (4) 'BlockRoots'
	b.BlockRoots = make([][]byte, 64)
	for ii := 0; ii < 64; ii++ {
		b.BlockRoots[ii] = append(b.BlockRoots[ii], buf[136:2184][ii*32:(ii+1)*32]...)
	}

	// Field (5) 'StateRoots'
	b.StateRoots = make([][]byte, 64)
	for ii := 0; ii < 64; ii++ {
		b.StateRoots[ii] = append(b.StateRoots[ii], buf[2184:4232][ii*32:(ii+1)*32]...)
	}

	// Offset (6) 'HistoricalRoots'
	if o6 = ssz.ReadOffset(buf[4232:4236]); o6 > size {
		return errOffset
	}

	// Field (7) 'Eth1Data'
	if b.Eth1Data == nil {
		b.Eth1Data = new(Eth1Data)
	}
	if err = b.Eth1Data.Unmarshal(buf[4236:4308]); err != nil {
		return err
	}

	// Offset (8) 'Eth1DataVotes'
	if o8 = ssz.ReadOffset(buf[4308:4312]); o8 > size || o6 > o8 {
		return errOffset
	}

	// Field (9) 'Eth1DepositIndex'
	b.Eth1DepositIndex = ssz.UnmarshallUint64(buf[4312:4320])

	// Offset (10) 'Validators'
	if o10 = ssz.ReadOffset(buf[4320:4324]); o10 > size || o8 > o10 {
		return errOffset
	}

	// Offset (11) 'Balances'
	if o11 = ssz.ReadOffset(buf[4324:4328]); o11 > size || o10 > o11 {
		return errOffset
	}

	// Field (12) 'RandaoMixes'
	b.RandaoMixes = make([][]byte, 64)
	for ii := 0; ii < 64; ii++ {
		b.RandaoMixes[ii] = append(b.RandaoMixes[ii], buf[4328:6376][ii*32:(ii+1)*32]...)
	}

	// Field (13) 'Slashings'
	b.Slashings = ssz.ExtendUint64(b.Slashings, 64)
	for ii := 0; ii < 64; ii++ {
		b.Slashings[ii] = ssz.UnmarshallUint64(buf[6376:6888][ii*8 : (ii+1)*8])
	}

	// Offset (14) 'PreviousEpochAttestations'
	if o14 = ssz.ReadOffset(buf[6888:6892]); o14 > size || o11 > o14 {
		return errOffset
	}

	// Offset (15) 'CurrentEpochAttestations'
	if o15 = ssz.ReadOffset(buf[6892:6896]); o15 > size || o14 > o15 {
		return errOffset
	}

	// Field (16) 'JustificationBits'
	b.JustificationBits = append(b.JustificationBits, buf[6896:6897]...)

	// Field (17) 'PreviousJustifiedCheckpoint'
	if b.PreviousJustifiedCheckpoint == nil {
		b.PreviousJustifiedCheckpoint = new(Checkpoint)
	}
	if err = b.PreviousJustifiedCheckpoint.Unmarshal(buf[6897:6937]); err != nil {
		return err
	}

	// Field (18) 'CurrentJustifiedCheckpoint'
	if b.CurrentJustifiedCheckpoint == nil {
		b.CurrentJustifiedCheckpoint = new(Checkpoint)
	}
	if err = b.CurrentJustifiedCheckpoint.Unmarshal(buf[6937:6977]); err != nil {
		return err
	}

	// Field (19) 'FinalizedCheckpoint'
	if b.FinalizedCheckpoint == nil {
		b.FinalizedCheckpoint = new(Checkpoint)
	}
	if err = b.FinalizedCheckpoint.Unmarshal(buf[6977:7017]); err != nil {
		return err
	}

	// Field (6) 'HistoricalRoots'
	{
		buf = tail[o6:o8]
		num, ok := ssz.DivideInt(len(buf), 32)
		if !ok {
			return errDivideInt
		}
		if num > 16777216 {
			return errListTooBig
		}
		b.HistoricalRoots = make([][]byte, num)
		for ii := 0; ii < num; ii++ {
			b.HistoricalRoots[ii] = append(b.HistoricalRoots[ii], buf[ii*32:(ii+1)*32]...)
		}
	}

	// Field (8) 'Eth1DataVotes'
	{
		buf = tail[o8:o10]
		num, ok := ssz.DivideInt(len(buf), 72)
		if !ok {
			return errDivideInt
		}
		if num > 1024 {
			return errListTooBig
		}
		b.Eth1DataVotes = make([]*Eth1Data, num)
		for ii := 0; ii < num; ii++ {
			if b.Eth1DataVotes[ii] == nil {
				b.Eth1DataVotes[ii] = new(Eth1Data)
			}
			if err = b.Eth1DataVotes[ii].Unmarshal(buf[ii*72 : (ii+1)*72]); err != nil {
				return err
			}
		}
	}

	// Field (10) 'Validators'
	{
		buf = tail[o10:o11]
		num, ok := ssz.DivideInt(len(buf), 121)
		if !ok {
			return errDivideInt
		}
		if num > 1099511627776 {
			return errListTooBig
		}
		b.Validators = make([]*Validator, num)
		for ii := 0; ii < num; ii++ {
			if b.Validators[ii] == nil {
				b.Validators[ii] = new(Validator)
			}
			if err = b.Validators[ii].Unmarshal(buf[ii*121 : (ii+1)*121]); err != nil {
				return err
			}
		}
	}

	// Field (11) 'Balances'
	{
		buf = tail[o11:o14]
		num, ok := ssz.DivideInt(len(buf), 8)
		if !ok {
			return errDivideInt
		}
		if num > 1099511627776 {
			return errListTooBig
		}
		b.Balances = ssz.ExtendUint64(b.Balances, num)
		for ii := 0; ii < num; ii++ {
			b.Balances[ii] = ssz.UnmarshallUint64(buf[ii*8 : (ii+1)*8])
		}
	}

	// Field (14) 'PreviousEpochAttestations'
	{
		buf = tail[o14:o15]
		num, err := ssz.DecodeDynamicLength(buf, 4096)
		if err != nil {
			return err
		}
		b.PreviousEpochAttestations = make([]*PendingAttestation, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if b.PreviousEpochAttestations[indx] == nil {
				b.PreviousEpochAttestations[indx] = new(PendingAttestation)
			}
			if err = b.PreviousEpochAttestations[indx].Unmarshal(buf); err != nil {
				return err
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	// Field (15) 'CurrentEpochAttestations'
	{
		buf = tail[o15:]
		num, err := ssz.DecodeDynamicLength(buf, 4096)
		if err != nil {
			return err
		}
		b.CurrentEpochAttestations = make([]*PendingAttestation, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if b.CurrentEpochAttestations[indx] == nil {
				b.CurrentEpochAttestations[indx] = new(PendingAttestation)
			}
			if err = b.CurrentEpochAttestations[indx].Unmarshal(buf); err != nil {
				return err
			}
			return nil
		})
		if err != nil {
			return err
		}
	}
	return err
}

// Size returns the ssz encoded size in bytes for the BeaconState object
func (b *BeaconState) Size() (size int) {
	size = 7017

	// Field (6) 'HistoricalRoots'
	size += len(b.HistoricalRoots) * 32

	// Field (8) 'Eth1DataVotes'
	size += len(b.Eth1DataVotes) * 72

	// Field (10) 'Validators'
	size += len(b.Validators) * 121

	// Field (11) 'Balances'
	size += len(b.Balances) * 8

	// Field (14) 'PreviousEpochAttestations'
	for ii := 0; ii < len(b.PreviousEpochAttestations); ii++ {
		size += 4
		size += b.PreviousEpochAttestations[ii].Size()
	}

	// Field (15) 'CurrentEpochAttestations'
	for ii := 0; ii < len(b.CurrentEpochAttestations); ii++ {
		size += 4
		size += b.CurrentEpochAttestations[ii].Size()
	}

	return
}

// Marshal ssz marshals the BeaconBlock object
func (b *BeaconBlock) Marshal() ([]byte, error) {
	buf := make([]byte, b.Size())
	return b.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the BeaconBlock object to a target array
func (b *BeaconBlock) MarshalTo(dst []byte) ([]byte, error) {
	var err error
	offset := int(76)

	// Field (0) 'Slot'
	dst = ssz.MarshalUint64(dst, b.Slot)

	// Field (1) 'ParentRoot'
	if dst, err = ssz.MarshalFixedBytes(dst, b.ParentRoot, 32); err != nil {
		return nil, errMarshalFixedBytes
	}

	// Field (2) 'StateRoot'
	if dst, err = ssz.MarshalFixedBytes(dst, b.StateRoot, 32); err != nil {
		return nil, errMarshalFixedBytes
	}

	// Offset (3) 'Body'
	dst = ssz.WriteOffset(dst, offset)
	offset += b.Body.Size()

	// Field (3) 'Body'
	if dst, err = b.Body.MarshalTo(dst); err != nil {
		return nil, err
	}

	return dst, err
}

// Unmarshal ssz unmarshals the BeaconBlock object
func (b *BeaconBlock) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 76 {
		return errSize
	}

	tail := buf
	var o3 uint64

	// Field (0) 'Slot'
	b.Slot = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'ParentRoot'
	b.ParentRoot = append(b.ParentRoot, buf[8:40]...)

	// Field (2) 'StateRoot'
	b.StateRoot = append(b.StateRoot, buf[40:72]...)

	// Offset (3) 'Body'
	if o3 = ssz.ReadOffset(buf[72:76]); o3 > size {
		return errOffset
	}

	// Field (3) 'Body'
	{
		buf = tail[o3:]
		if b.Body == nil {
			b.Body = new(BeaconBlockBody)
		}
		if err = b.Body.Unmarshal(buf); err != nil {
			return err
		}
	}
	return err
}

// Size returns the ssz encoded size in bytes for the BeaconBlock object
func (b *BeaconBlock) Size() (size int) {
	size = 76

	// Field (3) 'Body'
	size += b.Body.Size()

	return
}

// Marshal ssz marshals the SignedBeaconBlock object
func (s *SignedBeaconBlock) Marshal() ([]byte, error) {
	buf := make([]byte, s.Size())
	return s.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the SignedBeaconBlock object to a target array
func (s *SignedBeaconBlock) MarshalTo(dst []byte) ([]byte, error) {
	var err error
	offset := int(100)

	// Offset (0) 'Block'
	dst = ssz.WriteOffset(dst, offset)
	offset += s.Block.Size()

	// Field (1) 'Signature'
	if dst, err = ssz.MarshalFixedBytes(dst, s.Signature, 96); err != nil {
		return nil, errMarshalFixedBytes
	}

	// Field (0) 'Block'
	if dst, err = s.Block.MarshalTo(dst); err != nil {
		return nil, err
	}

	return dst, err
}

// Unmarshal ssz unmarshals the SignedBeaconBlock object
func (s *SignedBeaconBlock) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 100 {
		return errSize
	}

	tail := buf
	var o0 uint64

	// Offset (0) 'Block'
	if o0 = ssz.ReadOffset(buf[0:4]); o0 > size {
		return errOffset
	}

	// Field (1) 'Signature'
	s.Signature = append(s.Signature, buf[4:100]...)

	// Field (0) 'Block'
	{
		buf = tail[o0:]
		if s.Block == nil {
			s.Block = new(BeaconBlock)
		}
		if err = s.Block.Unmarshal(buf); err != nil {
			return err
		}
	}
	return err
}

// Size returns the ssz encoded size in bytes for the SignedBeaconBlock object
func (s *SignedBeaconBlock) Size() (size int) {
	size = 100

	// Field (0) 'Block'
	size += s.Block.Size()

	return
}

// Marshal ssz marshals the Transfer object
func (t *Transfer) Marshal() ([]byte, error) {
	buf := make([]byte, t.Size())
	return t.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the Transfer object to a target array
func (t *Transfer) MarshalTo(dst []byte) ([]byte, error) {
	var err error

	// Field (0) 'Sender'
	dst = ssz.MarshalUint64(dst, t.Sender)

	// Field (1) 'Recipient'
	dst = ssz.MarshalUint64(dst, t.Recipient)

	// Field (2) 'Amount'
	dst = ssz.MarshalUint64(dst, t.Amount)

	// Field (3) 'Fee'
	dst = ssz.MarshalUint64(dst, t.Fee)

	// Field (4) 'Slot'
	dst = ssz.MarshalUint64(dst, t.Slot)

	// Field (5) 'Pubkey'
	if dst, err = ssz.MarshalFixedBytes(dst, t.Pubkey, 48); err != nil {
		return nil, errMarshalFixedBytes
	}

	// Field (6) 'Signature'
	if dst, err = ssz.MarshalFixedBytes(dst, t.Signature, 96); err != nil {
		return nil, errMarshalFixedBytes
	}

	return dst, err
}

// Unmarshal ssz unmarshals the Transfer object
func (t *Transfer) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 184 {
		return errSize
	}

	// Field (0) 'Sender'
	t.Sender = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'Recipient'
	t.Recipient = ssz.UnmarshallUint64(buf[8:16])

	// Field (2) 'Amount'
	t.Amount = ssz.UnmarshallUint64(buf[16:24])

	// Field (3) 'Fee'
	t.Fee = ssz.UnmarshallUint64(buf[24:32])

	// Field (4) 'Slot'
	t.Slot = ssz.UnmarshallUint64(buf[32:40])

	// Field (5) 'Pubkey'
	t.Pubkey = append(t.Pubkey, buf[40:88]...)

	// Field (6) 'Signature'
	t.Signature = append(t.Signature, buf[88:184]...)

	return err
}

// Size returns the ssz encoded size in bytes for the Transfer object
func (t *Transfer) Size() (size int) {
	size = 184
	return
}

// Marshal ssz marshals the BeaconBlockBody object
func (b *BeaconBlockBody) Marshal() ([]byte, error) {
	buf := make([]byte, b.Size())
	return b.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the BeaconBlockBody object to a target array
func (b *BeaconBlockBody) MarshalTo(dst []byte) ([]byte, error) {
	var err error
	offset := int(220)

	// Field (0) 'RandaoReveal'
	if dst, err = ssz.MarshalFixedBytes(dst, b.RandaoReveal, 96); err != nil {
		return nil, errMarshalFixedBytes
	}

	// Field (1) 'Eth1Data'
	if dst, err = b.Eth1Data.MarshalTo(dst); err != nil {
		return nil, err
	}

	// Field (2) 'Graffiti'
	if dst, err = ssz.MarshalFixedBytes(dst, b.Graffiti, 32); err != nil {
		return nil, errMarshalFixedBytes
	}

	// Offset (3) 'ProposerSlashings'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.ProposerSlashings) * 408

	// Offset (4) 'AttesterSlashings'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(b.AttesterSlashings); ii++ {
		offset += 4
		offset += b.AttesterSlashings[ii].Size()
	}

	// Offset (5) 'Attestations'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(b.Attestations); ii++ {
		offset += 4
		offset += b.Attestations[ii].Size()
	}

	// Offset (6) 'Deposits'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.Deposits) * 1240

	// Offset (7) 'VoluntaryExits'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(b.VoluntaryExits) * 112

	// Field (3) 'ProposerSlashings'
	if len(b.ProposerSlashings) > 16 {
		return nil, errMarshalList
	}
	for ii := 0; ii < len(b.ProposerSlashings); ii++ {
		if dst, err = b.ProposerSlashings[ii].MarshalTo(dst); err != nil {
			return nil, err
		}
	}

	// Field (4) 'AttesterSlashings'
	if len(b.AttesterSlashings) > 1 {
		return nil, errMarshalList
	}
	{
		offset = 4 * len(b.AttesterSlashings)
		for ii := 0; ii < len(b.AttesterSlashings); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += b.AttesterSlashings[ii].Size()
		}
	}
	for ii := 0; ii < len(b.AttesterSlashings); ii++ {
		if dst, err = b.AttesterSlashings[ii].MarshalTo(dst); err != nil {
			return nil, err
		}
	}

	// Field (5) 'Attestations'
	if len(b.Attestations) > 128 {
		return nil, errMarshalList
	}
	{
		offset = 4 * len(b.Attestations)
		for ii := 0; ii < len(b.Attestations); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += b.Attestations[ii].Size()
		}
	}
	for ii := 0; ii < len(b.Attestations); ii++ {
		if dst, err = b.Attestations[ii].MarshalTo(dst); err != nil {
			return nil, err
		}
	}

	// Field (6) 'Deposits'
	if len(b.Deposits) > 16 {
		return nil, errMarshalList
	}
	for ii := 0; ii < len(b.Deposits); ii++ {
		if dst, err = b.Deposits[ii].MarshalTo(dst); err != nil {
			return nil, err
		}
	}

	// Field (7) 'VoluntaryExits'
	if len(b.VoluntaryExits) > 16 {
		return nil, errMarshalList
	}
	for ii := 0; ii < len(b.VoluntaryExits); ii++ {
		if dst, err = b.VoluntaryExits[ii].MarshalTo(dst); err != nil {
			return nil, err
		}
	}

	return dst, err
}

// Unmarshal ssz unmarshals the BeaconBlockBody object
func (b *BeaconBlockBody) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 220 {
		return errSize
	}

	tail := buf
	var o3, o4, o5, o6, o7 uint64

	// Field (0) 'RandaoReveal'
	b.RandaoReveal = append(b.RandaoReveal, buf[0:96]...)

	// Field (1) 'Eth1Data'
	if b.Eth1Data == nil {
		b.Eth1Data = new(Eth1Data)
	}
	if err = b.Eth1Data.Unmarshal(buf[96:168]); err != nil {
		return err
	}

	// Field (2) 'Graffiti'
	b.Graffiti = append(b.Graffiti, buf[168:200]...)

	// Offset (3) 'ProposerSlashings'
	if o3 = ssz.ReadOffset(buf[200:204]); o3 > size {
		return errOffset
	}

	// Offset (4) 'AttesterSlashings'
	if o4 = ssz.ReadOffset(buf[204:208]); o4 > size || o3 > o4 {
		return errOffset
	}

	// Offset (5) 'Attestations'
	if o5 = ssz.ReadOffset(buf[208:212]); o5 > size || o4 > o5 {
		return errOffset
	}

	// Offset (6) 'Deposits'
	if o6 = ssz.ReadOffset(buf[212:216]); o6 > size || o5 > o6 {
		return errOffset
	}

	// Offset (7) 'VoluntaryExits'
	if o7 = ssz.ReadOffset(buf[216:220]); o7 > size || o6 > o7 {
		return errOffset
	}

	// Field (3) 'ProposerSlashings'
	{
		buf = tail[o3:o4]
		num, ok := ssz.DivideInt(len(buf), 408)
		if !ok {
			return errDivideInt
		}
		if num > 16 {
			return errListTooBig
		}
		b.ProposerSlashings = make([]*ProposerSlashing, num)
		for ii := 0; ii < num; ii++ {
			if b.ProposerSlashings[ii] == nil {
				b.ProposerSlashings[ii] = new(ProposerSlashing)
			}
			if err = b.ProposerSlashings[ii].Unmarshal(buf[ii*408 : (ii+1)*408]); err != nil {
				return err
			}
		}
	}

	// Field (4) 'AttesterSlashings'
	{
		buf = tail[o4:o5]
		num, err := ssz.DecodeDynamicLength(buf, 1)
		if err != nil {
			return err
		}
		b.AttesterSlashings = make([]*AttesterSlashing, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if b.AttesterSlashings[indx] == nil {
				b.AttesterSlashings[indx] = new(AttesterSlashing)
			}
			if err = b.AttesterSlashings[indx].Unmarshal(buf); err != nil {
				return err
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	// Field (5) 'Attestations'
	{
		buf = tail[o5:o6]
		num, err := ssz.DecodeDynamicLength(buf, 128)
		if err != nil {
			return err
		}
		b.Attestations = make([]*Attestation, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if b.Attestations[indx] == nil {
				b.Attestations[indx] = new(Attestation)
			}
			if err = b.Attestations[indx].Unmarshal(buf); err != nil {
				return err
			}
			return nil
		})
		if err != nil {
			return err
		}
	}

	// Field (6) 'Deposits'
	{
		buf = tail[o6:o7]
		num, ok := ssz.DivideInt(len(buf), 1240)
		if !ok {
			return errDivideInt
		}
		if num > 16 {
			return errListTooBig
		}
		b.Deposits = make([]*Deposit, num)
		for ii := 0; ii < num; ii++ {
			if b.Deposits[ii] == nil {
				b.Deposits[ii] = new(Deposit)
			}
			if err = b.Deposits[ii].Unmarshal(buf[ii*1240 : (ii+1)*1240]); err != nil {
				return err
			}
		}
	}

	// Field (7) 'VoluntaryExits'
	{
		buf = tail[o7:]
		num, ok := ssz.DivideInt(len(buf), 112)
		if !ok {
			return errDivideInt
		}
		if num > 16 {
			return errListTooBig
		}
		b.VoluntaryExits = make([]*SignedVoluntaryExit, num)
		for ii := 0; ii < num; ii++ {
			if b.VoluntaryExits[ii] == nil {
				b.VoluntaryExits[ii] = new(SignedVoluntaryExit)
			}
			if err = b.VoluntaryExits[ii].Unmarshal(buf[ii*112 : (ii+1)*112]); err != nil {
				return err
			}
		}
	}
	return err
}

// Size returns the ssz encoded size in bytes for the BeaconBlockBody object
func (b *BeaconBlockBody) Size() (size int) {
	size = 220

	// Field (3) 'ProposerSlashings'
	size += len(b.ProposerSlashings) * 408

	// Field (4) 'AttesterSlashings'
	for ii := 0; ii < len(b.AttesterSlashings); ii++ {
		size += 4
		size += b.AttesterSlashings[ii].Size()
	}

	// Field (5) 'Attestations'
	for ii := 0; ii < len(b.Attestations); ii++ {
		size += 4
		size += b.Attestations[ii].Size()
	}

	// Field (6) 'Deposits'
	size += len(b.Deposits) * 1240

	// Field (7) 'VoluntaryExits'
	size += len(b.VoluntaryExits) * 112

	return
}

// Marshal ssz marshals the SignedBeaconBlockHeader object
func (s *SignedBeaconBlockHeader) Marshal() ([]byte, error) {
	buf := make([]byte, s.Size())
	return s.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the SignedBeaconBlockHeader object to a target array
func (s *SignedBeaconBlockHeader) MarshalTo(dst []byte) ([]byte, error) {
	var err error

	// Field (0) 'Header'
	if dst, err = s.Header.MarshalTo(dst); err != nil {
		return nil, err
	}

	// Field (1) 'Signature'
	if dst, err = ssz.MarshalFixedBytes(dst, s.Signature, 96); err != nil {
		return nil, errMarshalFixedBytes
	}

	return dst, err
}

// Unmarshal ssz unmarshals the SignedBeaconBlockHeader object
func (s *SignedBeaconBlockHeader) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 200 {
		return errSize
	}

	// Field (0) 'Header'
	if s.Header == nil {
		s.Header = new(BeaconBlockHeader)
	}
	if err = s.Header.Unmarshal(buf[0:104]); err != nil {
		return err
	}

	// Field (1) 'Signature'
	s.Signature = append(s.Signature, buf[104:200]...)

	return err
}

// Size returns the ssz encoded size in bytes for the SignedBeaconBlockHeader object
func (s *SignedBeaconBlockHeader) Size() (size int) {
	size = 200
	return
}

// Marshal ssz marshals the BeaconBlockHeader object
func (b *BeaconBlockHeader) Marshal() ([]byte, error) {
	buf := make([]byte, b.Size())
	return b.MarshalTo(buf[:0])
}

// MarshalTo ssz marshals the BeaconBlockHeader object to a target array
func (b *BeaconBlockHeader) MarshalTo(dst []byte) ([]byte, error) {
	var err error

	// Field (0) 'Slot'
	dst = ssz.MarshalUint64(dst, b.Slot)

	// Field (1) 'ParentRoot'
	if dst, err = ssz.MarshalFixedBytes(dst, b.ParentRoot, 32); err != nil {
		return nil, errMarshalFixedBytes
	}

	// Field (2) 'StateRoot'
	if dst, err = ssz.MarshalFixedBytes(dst, b.StateRoot, 32); err != nil {
		return nil, errMarshalFixedBytes
	}

	// Field (3) 'BodyRoot'
	if dst, err = ssz.MarshalFixedBytes(dst, b.BodyRoot, 32); err != nil {
		return nil, errMarshalFixedBytes
	}

	return dst, err
}

// Unmarshal ssz unmarshals the BeaconBlockHeader object
func (b *BeaconBlockHeader) Unmarshal(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 104 {
		return errSize
	}

	// Field (0) 'Slot'
	b.Slot = ssz.UnmarshallUint64(buf[0:8])

	// Field (1) 'ParentRoot'
	b.ParentRoot = append(b.ParentRoot, buf[8:40]...)

	// Field (2) 'StateRoot'
	b.StateRoot = append(b.StateRoot, buf[40:72]...)

	// Field (3) 'BodyRoot'
	b.BodyRoot = append(b.BodyRoot, buf[72:104]...)

	return err
}

// Size returns the ssz encoded size in bytes for the BeaconBlockHeader object
func (b *BeaconBlockHeader) Size() (size int) {
	size = 104
	return
}
